fix(argus): fix for frequent update calls
logicmonitor/helm-charts-qa pull request #201
Opened 2023-03-24 09:33 UTC by gurusiddha

2023-03-28 07:21 UTC, rohitphatak requested changes

2023-03-28 07:21 UTC, rohitphatak commented on charts/argus/values.schema.json
> +          "title": "Labelss settings",
Typo in Labels

2023-03-28 07:41 UTC, gurusiddha commented on charts/argus/values.schema.json
> +          "title": "Labelss settings",
fixed 👍

2023-03-30 08:54 UTC, shubhashri12 approved these changes

2023-03-30 09:42 UTC, vkumbhar94 approved these changes

2023-03-30 10:16 UTC, rohitphatak approved these changes

2023-03-30 10:17 UTC, merged