feat(affinity-rule): configurable affinity rule
logicmonitor/helm-charts-qa pull request #212
Opened 2023-04-17 17:48 UTC by shubhashri12

Added schema for affinity param for collector pod.

2023-04-18 10:11 UTC, vkumbhar94 requested changes

2023-04-18 11:32 UTC, shubhashri12 commented on charts/argus/templates/collectorset.yaml
> +    registry: {{ .Values.collector.image.registry | default (.Values.global.image.registry | default "docker.io") }}
It was unrelated, removed.

2023-04-19 06:41 UTC, sagarmamdapure approved these changes

2023-04-19 06:47 UTC, vkumbhar94 approved these changes

2023-04-19 06:48 UTC, rohitphatak approved these changes

2023-04-19 06:49 UTC, merged